[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.8.2"
  CI = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max_old_space_size=4096" 