[build]
  command = "npm install && npx expo export --platform web"
  publish = "web-build"

[context.production]
  command = "npm install && npx expo export --platform web"

[context.develop]
  command = "npm install && npx expo export --platform web"

[context.branch-deploy]
  command = "npm install && npx expo export --platform web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false" 