[build]
  command = "CI=false npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.8.2"
  NODE_ENV = "production" 