[build]
  command = "npm install --legacy-peer-deps --prefer-offline && NODE_ENV=production CI=false DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.8.2"
  NODE_OPTIONS = "--max-old-space-size=4096" 